apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-ov0q
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-upaw-tenant/test-app-qlup/devfile-sample-python-basic-ov0q@sha256:63be0b9579d502765c10bf2ab0316dc06f7aad8afa5dbdb334faf3f4196dcb18
        name: my-python
        resources: {}
status: {}
